import asyncio
import os
from dotenv import load_dotenv

from collections.abc import Iterator
from goldenverba.components.generation.interface import Generator
from wasabi import msg

load_dotenv()

class GPT4Generator(Generator):
    """
    GPT4 Generator.
    """

    def __init__(self):
        super().__init__()
        self.name = "GPT4Generator"
        self.description = "Generator using OpenAI's GPT-4-1106-preview model"
        self.requires_library = ["openai"]
        self.requires_env = ["OPENAI_API_KEY"]
        self.streamable = True
        self.model_name = os.getenv("OPENAI_MODEL","gpt-4-1106-preview")
        self.context_window = 10000


    async def generate(
        self,
        queries: list[str],
        context: list[str],
        conversation: dict = None,
        generate_rewriting_query: bool = False,
    ) -> str:
        """Generate an answer based on a list of queries and list of contexts, and includes conversational context
        @parameter: queries : list[str] - List of queries
        @parameter: context : list[str] - List of contexts
        @parameter: conversation : dict - Conversational context
        @parameter: generate_rewriting_query : bool - Flag to indicate if query rewriting should be performed
        @returns str - Answer generated by the Generator.
        """
        if conversation is None:
            conversation = {}

        # Select the appropriate function based on generate_rewriting_query flag
        if generate_rewriting_query:
            messages = self.prepare_rewrite_messages(queries, context, conversation)
        else:
            messages = self.prepare_messages(queries, context, conversation)

        total_char_length = sum(len(message["content"]) for message in messages)
        msg.info(f"Total number of characters entered into the {self.name} : {total_char_length}")

        try:
            import openai

            openai.api_key = os.getenv("OPENAI_API_KEY")

            if "OPENAI_API_TYPE" in os.environ:
                openai.api_type = os.getenv("OPENAI_API_TYPE")
            if "OPENAI_BASE_URL" in os.environ:
                openai.api_base = os.getenv("OPENAI_BASE_URL")
            if "OPENAI_API_VERSION" in os.environ:
                openai.api_version = os.getenv("OPENAI_API_VERSION")

            chat_completion_arguments = {
                "model": self.model_name,
                "messages": messages
            }
            if os.getenv("OPENAI_API_TYPE") == "azure":
                chat_completion_arguments["deployment_id"] = self.model_name

            completion = await asyncio.to_thread(
                openai.ChatCompletion.create, **chat_completion_arguments
            )
            system_msg = str(completion.choices[0].message.content)

            msg.good(f"Answer generated by {self.name} : {system_msg}")

        except Exception as e:
            # It's generally a good practice to catch more specific exceptions or handle them appropriately
            print(f"Error during message generation: {e}")
            raise

        return system_msg


    async def generate_stream(
        self,
        queries: list[str],
        context: list[str],
        conversation: dict = None,
    ) -> Iterator[dict]:
        """Generate a stream of response dicts based on a list of queries and list of contexts, and includes conversational context
        @parameter: queries : list[str] - List of queries
        @parameter: context : list[str] - List of contexts
        @parameter: conversation : dict - Conversational context
        @returns Iterator[dict] - Token response generated by the Generator in this format {system:TOKEN, finish_reason:stop or empty}.
        """
        if conversation is None:
            conversation = {}
        messages = self.prepare_messages(queries, context, conversation)

        total_char_length = sum(len(message["content"]) for message in messages)
        msg.info(f"Total number of characters entered into the {self.name} : {total_char_length}")

        try:
            import openai

            openai.api_key = os.getenv("OPENAI_API_KEY")
            base_url = os.environ.get("OPENAI_BASE_URL", "")
            if base_url:
                openai.api_base = base_url

            if "OPENAI_API_TYPE" in os.environ:
                openai.api_type = os.getenv("OPENAI_API_TYPE")
            if "OPENAI_API_BASE" in os.environ:
                openai.api_base = os.getenv("OPENAI_API_BASE")
            if "OPENAI_API_VERSION" in os.environ:
                openai.api_version = os.getenv("OPENAI_API_VERSION")            

            chat_completion_arguments = {
                "model":self.model_name,
                "messages":messages,
                "stream":True,
                "temperature":0.0
            }
            if openai.api_type=="azure":
                chat_completion_arguments["deployment_id"]=self.model_name            

            completion = await openai.ChatCompletion.acreate(
                **chat_completion_arguments
            )

            concatenated_response = ""  # 用于拼接响应内容的字符串

            try:
                while True:
                    chunk = await completion.__anext__()
                    if len(chunk["choices"]) > 0:
                        content = chunk["choices"][0]["delta"].get("content", "")
                        concatenated_response += content  # 累加消息内容
                        if "content" in chunk["choices"][0]["delta"]:
                            yield {
                                "message": chunk["choices"][0]["delta"]["content"],
                                "finish_reason": chunk["choices"][0]["finish_reason"],
                            }
                        else:
                            yield {
                                "message": "",
                                "finish_reason": chunk["choices"][0]["finish_reason"],
                            }
            except StopAsyncIteration:
                pass

            msg.good(f"Answer stream generated by {self.name} : {concatenated_response}")


        except Exception:
            raise

    def prepare_messages(
        self, queries: list[str], context: list[str], conversation: dict[str, str]
    ) -> list[dict[str, str]]:
        """
        Prepares a list of messages formatted for a Retrieval Augmented Generation chatbot system, including system instructions, previous conversation, and a new user query with context.

        @parameter queries: A list of strings representing the user queries to be answered.
        @parameter context: A list of strings representing the context information provided for the queries.
        @parameter conversation: A list of previous conversation messages that include the role and content.

        @returns A list of message dictionaries formatted for the chatbot. This includes an initial system message, the previous conversation messages, and the new user query encapsulated with the provided context.

        Each message in the list is a dictionary with 'role' and 'content' keys, where 'role' is either 'system' or 'user', and 'content' contains the relevant text. This will depend on the LLM used.
        """
        messages = [
            {
                "role": "system",
                "content": """You are a Retrieval Augmented Generation chatbot. Please answer user queries only their provided context. 
                The context is about the academic programs of the Faculty of Arts and Sciences at Queen's University.
                If the provided documentation does not provide enough information, say so, and explain why. """,
            }
        ]

        for message in conversation:
            messages.append({"role": message.type, "content": message.content})

        query = " ".join(queries)
        user_context = " ".join(context)

        messages.append(
            {
                "role": "user",
                "content": f"""The provided context: {user_context}. 
                These contexts are taken from the Queen's University Faculty of Arts and Sciences 
                Academic Programs database, which includes programme descriptions, requirements, 
                structures, and course offerings. The title of the document is between the 
                <document_title></document_title> tags, which represent which programme the document is about.
                 You need to differentiate between program and course, and focus on what the query is asking about.
                 Please answer this query: '{query}' with the provided context. """,
            }
        )

        return messages

    def prepare_rewrite_messages(
    self, queries: list[str], context: list[str], conversation: dict[str, str]
        ) -> list[dict[str, str]]:
        """
    Prepares a list of messages formatted for a system focused on enhancing and expanding user queries for more effective database retrieval. It includes system instructions, previous conversation, and a new user query with context aimed at generating a more detailed and comprehensive query.

        @parameter queries: A list of strings representing the user queries to be rewritten for completeness.
        @parameter context: A list of strings representing additional context information provided for the queries.
        @parameter conversation: A list of previous conversation messages that include the role and content.

        @returns A list of message dictionaries formatted to guide the generation of an expanded query. This includes an initial system message, the previous conversation messages, and a prompt for rewriting the user query with the provided additional context.

        Each message in the list is a dictionary with 'role' and 'content' keys, where 'role' is either 'system' or 'user', and 'content' contains the relevant text. This setup is intended to aid large language models in understanding the task of query rewriting.
        """
        messages = [
            {
                "role": "system",
                "content": """You are a query-answer system for queries about Queen's University Faculty of Arts and Sciences academic program. 
                Your task is to respond to the questions using the documents provided by the user and your knowledge of Queen's University Canada's academic programs.
                """,
                # "content": """You are a query augmentation system for the Queen's University Faculty of Arts and Sciences academic program database. 
                # Your task is to expand the original query question provided to you by the user, providing a better search query 
                # for database search engine, but no more than two sentences. 
                #   The user will also provide additional document for you to refer to when expanding. 
                #   You can also use your knowledge of Canada higher education system, particularly at Queen's University. 
                #   The new query you generated will be used in a search of Queen's University Faculty of Arts and Sciences Academic Programs database 
                #   (which includes descriptions, requirements, structures, and course offerings for all aspects of academic PROGRAMS, 
                #   as well as related course requirements and descriptions).
                  
                # Requirements for your response: If you can reason about the answer to the original query directly from the information provided by the user, you can also do so directly.
                # Otherwise, you can reply with a new augmentation query, 
                # which should be consistent with the overall form, and semantics of the original query. 
                # You can also expand the query by expanding the noun element, you can guess, enumerate, explain, 
                # correct, and expand the keywords of the original query. If there are technical terms or terms related to higher education system, please explain them. 
                # But you need to focus on what query is asking for. """,
            }
        ]



        
        #for message in conversation:
        #    messages.append({"role": message['type'], "content": message['content']})  # Adjusted to use dict access for consistency

        query = " ".join(queries)
        user_context = " ".join(context)

        messages.append(
            {
                "role": "user",
                "content": f""" Additional document: {user_context} .
                
                Requirements for your response: Prioritise answering with the information provided by the user.
                and if there is not enough information to answer the question, then use your knowledge about Queen's University 
                Canada's academic programs to answer. 
                When it is not possible to answer a query accurately, the use of synonyms, 
                or the presentation of strongly related concepts, is also encouraged.
                Your answer should be no more than three sentences.
                
                Write a passage that answers the given query:

                Query: What natural language processing related courses are on offer?
                Passage: Natural language processing (NLP), which is a branch of artificial intelligence
                that deals with the interaction between computers and human language.
                Related courses cover topics such as machine learning, artificial intelligence, data analytics, 
                and computational linguistics which are all relevant to the program. 
                At Queen's University, relevant courses for natural language processing include CISC 352 (Artificial
                Intelligence), CISC 452 (Neural and Genetic Computing), CISC 453 (Topics in
                Artificial Intelligence), CISC 473 (Deep Learning), COGS 201 (Cognition and
                Computation), and LING 415 (Semantics). 

                Query: How to get graduation with First Class Honours? 
                Passage:  The provided context does not include specific information about 
                the criteria for graduating with First Class Honours at Queen's University. 
                Typically, such criteria would involve maintaining a certain grade point average (GPA) 
                or achieving a specific standing in your courses. "How to get graduation with First Class Honours"
                is strongly associated with academic achievements, department specifics, and grading standards.

                Query: List the finance related programs? 
                Passage: Programs related to the field of finance would typically involve the study of 
                economics, accounting, business strategies, and market analysis.
                At Queen's University, the program closest to finance within the 
                Faculty of Arts and Sciences would be Economics, with various levels of study
                such as Economics - Major (Arts) – Bachelor of Arts (Honours), Economics – Joint
                Honours (Arts) – Bachelor of Arts (Honours), and Economics – Minor (Arts).

                Query: How many transfer credits can a student receive at most?
                Passage:
                Questions regarding the maximum number of transfer credits a student can receive are 
                typically found in sections such as "Admission Requirements" or "Transfer Policies," 
                which detail the acceptance criteria and limits for transferring credits into a program.
                Keywords such as “transfer credits,” “credit acceptance,” “maximum transfer credits,” 
                and “transfer policy” can be useful in locating this information. 
                
                Query: Please compare the main differences between the Art History Joint Honours and Art History General programs
                Passage: The information provided is not sufficient to answer this question fully. 
                However, it can be surmised that The History of Art Joint Honours programme is more 
                specialized, pairing History of Art with another discipline for a Joint Honours degree, 
                whereas the Art History General Programme is less specialized, 
                offering greater flexibility and more electives without leading to an honours degree..
                
                Query: Is the internship available to students from all departments within the Faculty of Arts and Science?
                Passage: The provided documents do not contain specific information regarding the availability of internships to 
                students from all departments within the Faculty of Arts and Science at Queen's
                University. Internship opportunities and their eligibility criteria can vary by
                program and department, and such details are typically outlined in
                program-specific handbooks or on the university's career services website.


                
                Query: {query}
                Passage: """,
                # "content": f""" Additional document: {user_context} .
                # If you can reason about the answer to the original query directly from the information provided by the user, you can also do so directly. 
                # If the original query is relevant to document information,
                # the use of document information to guess the semantics of the original query, 
                # for element completion and augmentation is encouraged. 
                # if not relevant, use your knowledge about Canada higher education system, especially the education system 
                # of Queen's University, to augment the query. 
                # Using your knowledge, accomplishing the expansion by explaining some of the professional terms or terms 
                # related to higher education system in the original query is encouraged.
                # You can refer to your knowledge about the education system of Queen's University, and the additional document.
                # Based on the original query: '{query}', generate a new rewrite query. Your response should continue with 'Rewrite query:'.""",
            }
        )

        return messages
